sonar.projectKey=art-orient_authservice
sonar.organization=art-orient
sonar.host.url=https://sonarcloud.io

sonar.sources=src/main/java
sonar.tests=src/test/java

sonar.java.binaries=target/classes
sonar.junit.reportPaths=target/surefire-reports
sonar.jacoco.reportPaths=target/jacoco.exec